# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = yes
RGBLIGHT_ENABLE = yes
BOOTMAGIC_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
MOUSEKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
# COMBO_ENABLE = yes

# Trackball
POINTING_DEVICE_ENABLE = yes
# pmw3360 or pmw3389
POINTING_DEVICE_DRIVER = pmw3389
